// Objective-C API for talking to github.com/Jigsaw-Code/outline-apps/client/go/outline/tun2socks Go package.
//   gobind -lang=objc github.com/Jigsaw-Code/outline-apps/client/go/outline/tun2socks
//
// File is generated by gobind. Do not edit.

#ifndef __Tun2socks_H__
#define __Tun2socks_H__

@import Foundation;
#include "ref.h"
#include "Universe.objc.h"

#include "Outline.objc.h"
#include "Platerrors.objc.h"

@class Tun2socksConnectRemoteDeviceResult;
@class Tun2socksRemoteDevice;
@protocol Tun2socksTunWriter;
@class Tun2socksTunWriter;

@protocol Tun2socksTunWriter <NSObject>
- (BOOL)close:(NSError* _Nullable* _Nullable)error;
- (BOOL)write:(NSData* _Nullable)p0 n:(long* _Nullable)n error:(NSError* _Nullable* _Nullable)error;
@end

/**
 * ConnectRemoteDeviceResult represents the result of ConnectRemoteDevice.

We use a struct instead of a tuple to preserve a strongly typed error that gobind recognizes.
 */
@interface Tun2socksConnectRemoteDeviceResult : NSObject <goSeqRefInterface> {
}
@property(strong, readonly) _Nonnull id _ref;

- (nonnull instancetype)initWithRef:(_Nonnull id)ref;
- (nonnull instancetype)init;
@property (nonatomic) Tun2socksRemoteDevice* _Nullable device;
@property (nonatomic) PlaterrorsPlatformError* _Nullable error;
@end

/**
 * RemoteDevice is an IO device that connects to a remote Outline server.
It is also responsible for managing the Outline client session.

This type is exported through gomobile, and wraps a [vpn.RemoteDevice].
 */
@interface Tun2socksRemoteDevice : NSObject <goSeqRefInterface> {
}
@property(strong, readonly) _Nonnull id _ref;

- (nonnull instancetype)initWithRef:(_Nonnull id)ref;
- (nonnull instancetype)init;
- (PlaterrorsPlatformError* _Nullable)close;
- (PlaterrorsPlatformError* _Nullable)getHealthStatus;
- (void)notifyNetworkChanged;
- (BOOL)write:(NSData* _Nullable)p0 ret0_:(long* _Nullable)ret0_ error:(NSError* _Nullable* _Nullable)error;
@end

FOUNDATION_EXPORT Tun2socksConnectRemoteDeviceResult* _Nullable Tun2socksConnectRemoteDevice(OutlineClient* _Nullable client);

/**
 * GoRelayTraffic starts two goroutines to relay network traffic bidirectionally
between a TUN device (passed as a file descriptor) and a remote device.
 */
FOUNDATION_EXPORT PlaterrorsPlatformError* _Nullable Tun2socksGoRelayTraffic(long fd, Tun2socksRemoteDevice* _Nullable rd);

/**
 * GoRelayTrafficOneWay starts one goroutine to relay network traffic from
a remote device to a TUN device (passed as a [TunWriter]).
 */
FOUNDATION_EXPORT PlaterrorsPlatformError* _Nullable Tun2socksGoRelayTrafficOneWay(id<Tun2socksTunWriter> _Nullable tun, Tun2socksRemoteDevice* _Nullable rd);

@class Tun2socksTunWriter;

/**
 * TunWriter is an interface that allows for outputting packets to the TUN (VPN).

This type will be exposed to native code via gomobile.
 */
@interface Tun2socksTunWriter : NSObject <goSeqRefInterface, Tun2socksTunWriter> {
}
@property(strong, readonly) _Nonnull id _ref;

- (nonnull instancetype)initWithRef:(_Nonnull id)ref;
- (BOOL)close:(NSError* _Nullable* _Nullable)error;
- (BOOL)write:(NSData* _Nullable)p0 n:(long* _Nullable)n error:(NSError* _Nullable* _Nullable)error;
@end

#endif
